rock-core/tools-roby

lib/roby/app/scripts/shell.rb

Otherwise syskit shell cannot be called

Removed readline from utilrb, instead using ruby native readline

---

generators/robot/templates/robot.rb
lib/roby/app.rb

There were minor errors in Application#load_default_models, and the issue reported by #22
Closes #25

Make sure a freshly generated robot actually works

---

lib/roby/coordination/models/script.rb
test/coordination/test_task_script.rb

To ensure the event's presence, the implementation was adding the task
as a dependency. It was however setting up this dependency with the
waited-on event in success and remove_when_done set, which means that
the child was removed after the wait no matter what.
This changes the handling so that all code paths go through explicit
when_unreachable / on handling instead of using the dependency relation
to handle the checks. Moreover, it generates a unique role name so that
the dependency can be removed while leaving the existing relations
unchanged.

coordination: fix #wait in task scripts where the event is a task's child's

---

Gemfile

automatically install yard, if it was not already

add yard dependency

---

lib/roby/app.rb
lib/roby/cli/log.rb
lib/roby/execution_engine.rb
lib/roby/relations/bidirectional_directed_adjacency_graph.rb

Small improvements

---

lib/roby/actions/models/interface_base.rb
lib/roby/coordination/models/base.rb
lib/roby/coordination/models/event.rb
lib/roby/test/assertions.rb
test/coordination/models/test_action_state_machine.rb
test/test/test_assertions.rb

(See documentation of the method for more details)

define run_state_machine_capture to test capture blocks

---

lib/roby/app.rb
lib/roby/test/roby_app_helpers.rb
test/app/fixtures/define_action.rb
test/app/test_run.rb

This allows single-file "apps" to define models and load them.

app: allow additional model files to define new action interfaces

---

lib/roby/plan.rb
test/test_plan.rb

This is useful to "clean" plans when building them, without having
to add/remove tasks from the permanent or mission sets.

core: allow explicitly protecting tasks in static_garbage_collect

---

lib/roby/app.rb
lib/roby/droby/event_logger.rb
lib/roby/droby/event_logging.rb
lib/roby/droby/logfile.rb
lib/roby/droby/logfile/index.rb
lib/roby/droby/logfile/reader.rb
lib/roby/droby/logfile/writer.rb
lib/roby/promise.rb
lib/roby/support.rb
lib/roby/test/droby_log_helpers.rb
lib/roby/test/event_reporter.rb
test/droby/test_event_logger.rb
test/droby/test_logfile.rb

These are changes mainly useful for `syskit-log`

minor additions around logs

---

lib/roby/execution_engine.rb
lib/roby/interface/rest/server.rb

Modified REST API configuration to show errors instead of getting internal server error.

Show error

---

lib/roby/app/rake.rb

TESTOPTS is what Rake's default test task is expecting, pass it on
to minitest

app: pass the TESTOPTS environment variable to the underlying `roby test` call

---

lib/roby/coordination/script.rb
test/coordination/test_task_script.rb

coordination: fix corner cases in poll_until

---

lib/roby/app/cucumber/controller.rb
test/app/cucumber/test_controller.rb

The app sometimes fails to quit. Implement the timeout to at least
not have a complete freeze of the system (in e.g. CI) while we debug
the issue

app: implement timeout in the cucumber controller's roby_stop and roby_kill

---

lib/roby/app/cucumber/controller.rb

CI started failing with a NoMethodError for wants_to_quit. I checked
the versions, and they match between my local machine and the CI
environment. I'm clueless.

Workaround weird test failure

---

lib/roby/app.rb
lib/roby/robot.rb

It's called during setup, so people should really use .setup/on_setup

chore: add deprecation message on Robot.config / Application#on_config

---

lib/roby/app/rake.rb

The existing rake test helper class tries to be a "run all tests automatically" one-stop shop, which makes it very awkward to use in more complex configuration setups.
This new class runs a single test, allowing the bundle Rakefile to setup each test separately as it needs.

feat: define Roby:App::Rake::RobotTestTask to run tests for a single configuration

---

lib/roby/app/rake.rb
lib/roby/app/scripts/test.rb

fix: coverage support in `roby test`

---

lib/roby/app/scripts/test.rb
lib/roby/exceptions.rb
lib/roby/execution_engine.rb
lib/roby/task.rb
lib/roby/test/execution_expectations.rb
lib/roby/test/minitest_helpers.rb
lib/roby/test/minitest_plugin.rb
lib/roby/test/minitest_reporter.rb
test/task_structure/test_dependency.rb
test/test/test_execution_expectations.rb

fix: improve error reporting in tests

---

lib/roby/droby/plan_rebuilder.rb
lib/roby/droby/rebuilt_plan.rb
test/droby/test_event_logging.rb

Reverts rock-core/tools-roby#256

Revert "fix: fix a longstanding problem during log replay"

---

lib/roby/app/scripts/test.rb

Depends on:
The ROBOT pattern allows to specify robot-specific paths and files that will be resolved based on the robot name. This support was broken by the addition of the glob support, since the globbing would remove these files.
This commit resolves ROBOT for all arguments, including globs and *before* globbing gets resolved. In addition, it generates an error if a glob pattern does not match anything unless --allow-empty-globs is set.

fix: usage of the ROBOT pattern in test file specification

---

lib/roby/app.rb
lib/roby/app/scripts/run.rb
lib/roby/app/scripts/shell.rb
lib/roby/cli/base.rb
lib/roby/cli/main.rb
lib/roby/interface/interface.rb
lib/roby/interface/rest.rb
lib/roby/interface/v1/tcp.rb
lib/roby/interface/v2/async/action_monitor.rb
lib/roby/interface/v2/async/job_monitor.rb
lib/roby/interface/v2/channel.rb
lib/roby/interface/v2/client.rb
lib/roby/interface/v2/protocol.rb
lib/roby/interface/v2/server.rb
lib/roby/interface/v2/shell_client.rb
lib/roby/interface/v2/tcp.rb
lib/roby/test/roby_app_helpers.rb
test/app/test_run.rb
test/cli/test_display.rb
test/interface/v2/async/test_action_monitor.rb
test/interface/v2/test_client.rb
test/interface/v2/test_server.rb
test/test_app.rb

feat: add support for the v2 interface in CLI shell, run, wait, quit (on top of #274)

---

lib/roby/app/scripts/test.rb

Test files should be loaded just after the `require` configure step. {#prepare} prepares for execution.
Among other things, this fixes https://github.com/rock-core/tools-syskit/pull/422 for tests.

fix: require test files before Application#prepare

---

manifest.xml

chore: add irb dependency

---

test/test/test_assertions.rb

I changed the PR to add a unit test for this transition to serve as an example in the future. We should also update the documentation with an example. See the discussion below for the reasoning.
This can help when the action state machine transitions using another task's event (other than the toplevel task), i.e.
```
action_state_machine :sm do
first = state foo_def
second = state bar_def
final = state final_def
first.depends_on second
transition first, second.some_event, final
end
```
One would be able to use:
```
validate_state_machine ... do
....
assert_transitions_to_state(:final, yield_dependencies: true) do |first_state_task, *dependencies|
second_task = dependencies.select { _1.model.name == "second" }.task
execute { second_task.some_event.emit }
end
end
```

chore: add unit test for transitioning with a child state event on validate state machine

---

lib/roby/app/scripts/test.rb

Needed for running minitest after block

fix: run minitest after blocks

---

lib/roby/interface/rest/task.rb
test/interface/rest/test_task.rb

This breaks the general assumption in Roby (that an interrupted task is failed), and therefore things like error handling that would rely on it

fix: emit failed and not stop when a REST task is stopped

---

lib/roby/app/rake.rb

For e.g. dump of network graphs and/or core dumps

feat: allow to add the 'standard' roby logs to a package's test results

---

lib/roby/test/spec.rb

This ensures that any test that would forget to call it can be detected early. This was added because of such a test and an hour or two of debugging to find the problem.
Depends on:

fix: verify that timecop is not active in Spec#setup

---

lib/roby/task_arguments.rb
test/test_task_arguments.rb

DelayedArgumentFromState would merge only with itself. It the other task has a static argument with the same value than resolved with the state, it would not merge.
This is very restrictive, and is actually problematic in Syskit when e.g. from_conf is used in a TaskContext instance.
In that case, during network generation, Syskit itself freezes delayed arguments before during deployment. This causes the from_conf arguments to be replaced by their values.
Then, the deployer creates a task "from scratch" that has the from_conf. First bug here: the newly deployed task will not have the same arguments than the initial task.
And then it won't merge with the existing deployment, which causes yet-another-instance to be created. In that case, the visible symptom is that the task context gets …

fix: allow merging delayed arguments from state when the other arg has the same value

---

lib/roby/plan.rb
test/test_plan.rb

Reverts rock-core/tools-roby#236

Revert "feat: define Plan#useful_tasks_using"
