rock-core/tools-roby

lib/yard-roby.rb

This allows Roby apps to load these roby extensions as a YARD plugin
(e.g. with YARD's --plugin command line option)

add lib/yard-roby.rb to load the Roby-specific YARD extensions

---

lib/roby/app.rb

Robots were not found because common_opparse_setup runs before the
Roby.app is setup. Therefore, call setup_robot_names_from_config_dir to
make robots available.

App: fix option --robot

---

lib/roby/app.rb
lib/roby/app/scripts.rb
lib/roby/app/scripts/shell.rb
lib/roby/interface/tcp.rb
test/test_app.rb

This is required to be able to connect the various Roby/Syskit tools (including the IDE) to a syskit instance started on a non-standard port.

Fix host option

---

lib/roby/actions/models/action.rb
lib/roby/droby/v5/droby_dump.rb

A.k.a into the droby-specific parts

droby: move the droby-related Actions::Models::Actions#proxy and #proxy! methods to their proper place

---

lib/roby/app.rb
lib/roby/execution_engine.rb
lib/roby/interface/droby_channel.rb
lib/roby/interface/interface.rb
lib/roby/interface/server.rb
lib/roby/interface/tcp.rb
test/interface/test_droby_channel.rb
test/interface/test_server.rb

DRobyChannel now catches and interprets any SystemCallError as a
communication failure error.
Moreover, one can now set Server#abort_on_exception to false so that
any error in the read/write codepaths only cause a disconnection but
not a full Roby abort. The app-wide setting is in
Roby.app.shell_abort_on_exception.

interface: improve error codepaths related to Server (closes #64)

---

lib/roby/actions/models/action.rb
lib/roby/actions/models/interface_base.rb
test/coordination/models/test_action_state_machine.rb

The arguments were given wrongly, interpreting the { default: nil } hash
as the argument's documentation. Ensure that documentation is always a
string to avoid these problems in the future

coordination: fix definition of the 'start_state' argument in action state machines

---

lib/roby/actions/models/coordination_action.rb
lib/roby/droby/v5/droby_dump.rb
test/coordination/models/test_action_state_machine.rb

The coordination models will return an existing action on their
interface model. This means that the e.g. return type is marshalled on
the sending side, but not unmarshalled on the receiving side. Make sure
it is, and make sure that arguments are unmarshalled as well.

droby: fix model marshalling in interaction with coordination models

---

lib/roby/interface/async/interface.rb
lib/roby/interface/client.rb
test/interface/test_client.rb

Expose the api through Roby::Interface::Async::Interface
Add method to check whether an async call is still pending

interface: extend async call api

---

lib/roby/tasks/external_process.rb
test/tasks/test_external_process.rb

This is needed so that ExternalProcess can be used as a toplevel task.

fix Tasks::ExternalProcess so that it can be created without arguments

---

lib/roby/tasks/thread.rb
test/tasks/test_thread_task.rb

- cleanup the task to use Concurrent::Event instead of booleans
- allow subclasses to delay the emission of the start event
- make a difference between one-shot computation and permanent execution, to improve error handling in the latter case

tasks: improve Tasks::Thread

---

lib/roby/actions/models/coordination_action.rb
lib/roby/actions/models/method_action.rb
lib/roby/actions/task.rb
lib/roby/interface/interface.rb
lib/roby/task_structure/planned_by.rb
test/interface/test_interface.rb
test/relations/test_space.rb
test/task_structure/test_planned_by.rb

Among other things, this fixes issues in the IDE such as:
- actions that are alive and being executed but are shown as FINALIZED
- planning failed errors that would show up as FINALIZED, and not have the exception shown
- jobs that would not show up at all (when added within a transaction)

ui: fix interface job tracking bugs

---

.travis.yml
Gemfile
Rakefile
lib/roby.rb
lib/roby/app.rb
lib/roby/app/cucumber/controller.rb
lib/roby/app/scripts/shell.rb
lib/roby/interface/async/interface.rb
lib/roby/interface/droby_channel.rb
lib/roby/interface/shell_client.rb
lib/roby/interface/tcp.rb
lib/roby/test/aruba_minitest.rb
lib/roby/test/roby_app_helpers.rb
lib/roby/test/self.rb
roby.gemspec
test/cli/test_gen_main.rb
test/cli/test_main.rb
test/interface/async/client_server_test_helpers.rb
test/interface/test_client.rb
test/interface/test_shell_client.rb
test/interface/test_tcp.rb
test/tasks/test_thread_task.rb
test/test_app.rb

This _mostly_ fixes the build on travis. There are still a bunch of race conditions happening, related to app setup. But it's at least passing most of the time.
One necessary but possibly breaking change is https://github.com/rock-core/tools-roby/commit/6e78718fd79dabd82b676c02c0b3c12831eb0b2f. This commit adds an explicit check in DRobyChannel to ensure that a given channel is used only by a single thread. I have very little runtime setups to test it more thoroughly on, so it's definitely possible that it would break some existing UIs. Now, it's IMO for the best - this was a ticking bomb.
2.5.0 is allowed to fail as it definitely fails on directory/file handling and I don't have the time to investigate for now.

improve the build on travis

---

lib/roby/interface/droby_channel.rb
lib/roby/interface/server.rb
test/interface/test_server.rb

UI events are meant to be sent from various places in the system,
and are really meant to be forwarded to the outside interfaces.
It's not reasonable to require that they are all generated from
the event loop.
This fixes an actual bug where file watching in Syskit would send
an UI event (conf file change) which would then end up writing packets
in the wrong thread.

interface: make sure UI event notifications are MT-safe

---

lib/roby/app.rb
lib/roby/app/scripts/run.rb
lib/roby/coordination/models/base.rb

Syskit for instance needs to start/connect to the process server
in #setup (since we get the models from the process servers). The
current codepath was not cleaning this, which was leaking one
process server at each restart.

app: fix resource leak on restart due to not calling #clear

---

lib/roby/app.rb

Application has now #restart, it is being weird to have to quit
on the engine but restart on the application. Since restarting
is really done at the application-level, add #quit to Application
as well.

app: define #quit on Application

---

lib/roby/executable_plan.rb
lib/roby/relations/bidirectional_directed_adjacency_graph.rb
lib/roby/task.rb
lib/roby/task_arguments.rb
test/test_task_arguments.rb

The current policy was "all or nothing or everything". Either
1. the argument was set to an actual value, and it has to stay
at this value forever
2. the argument was set to a delayed value, and it could be
updated by anything
3. the argument was not set, and it could be set to anything
This was a bit of a ... limiting policy for the purpose of merging
plans (i.e. in Syskit). The functionality for which this was designed
(default arguments) worked just fine, a (1) and (2) are good policies
for it. For referenced arguments (the from(...) syntax), it leads to
merging things that ultimately point to completely different arguments.
To deal with the difference in semantic between the two types of
delayed arguments, and provide a framework to more flexibly handle
merging arguments in a plan …

improve handling of delayed arguments during merge

---

lib/roby/test/execution_expectations.rb
lib/roby/test/expect_execution.rb

It defines a block that is called at each execution cycle
instead of only once for the block given to expect_execution itself
For instance:
~~~
expect_execution.poll do
do something repeatedly
end.to do
expect something
end
~~~

test: define .poll() on the expect_execution object

---

lib/roby/app.rb

When a tool like the IDE is started, it attempts to delete all
directories that it had to create for its own log dir. However,
if in the meantime something like syskit run was executed, the
log directories end up not being empty
On Ruby 2.3, FileUtils.rmdir would simply ignore such directories.
2.5 raises Errno::ENOTEMPTY. Since Errno::ENOTEMPTY already exists
in 2.3 as well, let's just rescue it.

app: fix deleting created log base directories on 2.5

---

lib/roby.rb
lib/roby/app.rb
lib/roby/custom_require.rb

This is hopefully the last time I have to debug issues related to
this problem. It works without requiring that we modify the LOAD_PATH
too eagerly (the way the bundle mechanism worked)
One would only have to add
~~~
Roby.app.register_app('../common_models')
~~~
to the init code to get the common models bundle once and for all,
both through the 'common_models/models' or the direct 'models/' paths

implement a built-in depend-on-other-apps mechanism

---

lib/roby/cli/display.rb
lib/roby/droby/logfile/reader.rb
lib/roby/gui/log_display.rb
lib/roby/gui/plan_rebuilder_widget.rb

This allows more high-level tools to keep the data from the caches,
helping with e.g. cleanup and backups

cli: allow for a separation of the log file and its index

---

lib/roby/test/execution_expectations.rb
test/test/test_execution_expectations.rb

This is actually needed by Syskit, where the "has_no_new_sample" expectation will report
~~~
:0xXXXXXX<id:6910>(conf: [\"default\"], orocos_name: test).out should not have received a new sample, but it received one: 10
~~~
instead of the current
~~~
:0xXXXXXX<id:6910>(conf: [\"default\"], orocos_name: test).out should not have received a new sample, but did not because of 10
~~~

test: allow expectation subclasses to fine-tune the error messages

---

lib/roby/task_structure/dependency.rb
test/task_structure/test_dependency.rb

Syskit allows to represent one or more data services in the plan.
Until recently, the generated task models were having
'Syskit::Component' within their fullfilled model, but they're
actually not full components and they are not returning it anymore.
Change #provided_models to handle this use case, where
models.fullfilled_model only returns services (Ruby Module) and
no task models (Ruby Class)

handle model.fullfilled_model returning an array with no class

---

lib/roby/test/spec.rb

Minitest::Test#run is expected to return Minitest::Result instances.
Refactor to separately handling the roby_should_run call (for which
we do need to catch errors) and just call super for the rest - since
Minitest already internally wraps the call.

test: fix value returned by #run in Test::Spec

---

lib/roby/task.rb
lib/roby/task_arguments.rb

This is useful in error reporting, for instance in Syskit when a plan can't be merged.
In addition, improve the documentation regarding the handling of task arguments,
especially w.r.t. the difference between plain and delayed argument objects.

Provide a way to know why arguments don't get merged

---

lib/roby/cli/main.rb

It starts a pry session *after* having loaded the whole application.
Quite useful to play with the models.

cli: create 'console'

---

lib/roby/interface/rest/server.rb

Explicit the 'route prefix' to the api with 'api/' as default.

add route prefix to webapp

---

lib/roby/cli/gen/actions/class.rb.erb
lib/roby/cli/gen/actions/test.rb.erb
lib/roby/cli/gen/class/class.rb.erb
lib/roby/cli/gen/class/test.rb.erb
lib/roby/cli/gen/module/module.rb.erb
lib/roby/cli/gen/module/test.rb.erb
lib/roby/cli/gen/roby_app/config/init.rb
lib/roby/cli/gen/roby_app/config/robots/robot.rb.erb
lib/roby/cli/gen/task/class.rb.erb
lib/roby/cli/gen/task/test.rb.erb
lib/roby/cli/gen_main.rb

The old pattern will still work, to make sure gen is not broken if
we forget some files, and/or we're not breaking other packages
(e.g. Syskit) while they migrate too,.

rename all templates to .rb.erb to please IDE's syntax highlighting autodection

---

lib/roby/interface/client.rb
test/interface/test_client.rb

This ensures that client such as the shell or the IDE don't freeze
forever if Syskit has become unresponsive
I was originally going for a timeout: parameter, but it is tricky to
make the difference between a `timeout` argument to a remote call and a
timeout argument to the Client method. It would have needed a different
design from the get-go. So, go for a class-wide timeout instead.

shell: add a timeout on calls

---

lib/roby/test/dsl.rb
lib/roby/test/roby_app_helpers.rb
test/app/fixtures/run_if.rb
test/test/test_dsl.rb

Describe blocks that handle Roby/Syskit models already had the ability
to define tests that should run only in certain combination(s) of settings (e.g.
particular robot, `--live`, `--interactive`).
This extends that ability to contexts that describe non-Roby classes. They
only have to `include Roby::Test::DSL`.
The roby_should_run mechanism, which is the underlying implementation
for e.g. run_interactive was currently available only on Roby/Syskit-
related tests, as e.g. composition tests or task context tests.
This makes it available also for "plain" tests. The only requirement
is that the test needs to extend Roby::Test::DSL.

test: provide Test::InstanceExtension to allow filtering on robot/mode/... even on non-Roby contexts

---

lib/roby/test/expect_execution.rb
lib/roby/test/teardown_plans.rb
test/test/test_expect_execution.rb
test/test/test_teardown_plans.rb

So far, Roby/Syskit tests were always run in stub mode. Running them for live components
triggered some issues, mostly related to the fact that live components are handled asynchronously

small improvements for asynchronous tests

---

lib/roby/task.rb
test/test_task.rb

A task finishing is a running task, so running verification should be after finishing verification.

Fix task state verification to verify in the correct order.

---

lib/roby/app/scripts/test.rb

Running `roby test` in an app may run tests in dependent apps as well (e.g. in bundles/common_models). The current behavior of "anchoring" the exclusion patterns from `app_dir` made it pretty hard to use them.
This inverses the behavior: match the patterns as-is - thus allowing to exclude test files from dependent bundles - which still allows to explicitly provide a pattern with the name of a parent app to 'anchor' the pattern.

app: do not resolve test exclusions w.r.t the app dir

---

lib/roby/coordination/script.rb
lib/roby/coordination/task_script.rb
test/coordination/test_task_script.rb

If during execution the same event of a task is used sequentially in two state machines, the second transition will raise an exception if the first state machine has been garbage collected.
For instance, in:
~~~
action_state_machine 'test' do
wait = state(acquire_pose)
done = state(another).depends_on(acquire_pose)
transition wait.pose_acquired_event, done
done.success_event.forward_to success_event
end
~~~
if the `acquire_pose` toplevel task is not terminated between two runs of `test`, the second run would raise an exception.

fix exception when the same event of a task is sequentially used in two state machines

---

lib/roby/plan.rb
lib/roby/queries.rb
lib/roby/queries/and_matcher.rb
lib/roby/queries/index.rb
lib/roby/queries/local_query_result.rb
lib/roby/queries/matcher_base.rb
lib/roby/queries/not_matcher.rb
lib/roby/queries/op_matcher.rb
lib/roby/queries/or_matcher.rb
lib/roby/queries/plan_object_matcher.rb
lib/roby/queries/plan_query_result.rb
lib/roby/queries/query.rb
lib/roby/queries/task_event_generator_matcher.rb
lib/roby/queries/task_matcher.rb
lib/roby/queries/transaction_query_result.rb
lib/roby/transaction.rb
test/queries/test_and_matcher.rb
test/queries/test_not_matcher.rb
test/queries/test_or_matcher.rb
test/queries/test_query.rb
test/queries/test_task_event_generator_matcher.rb
test/queries/test_task_matcher.rb
test/test_transactions.rb

So far, the Query class was the only one that could be used to
find tasks matching a TaskMatcher inside a plan. With the
recent addition of all types of matchers (events, task events,
and/or/not) and the need to add a port matcher in Syskit, this
commit refactors the code to allow any type of matcher to iterate
over a plan.
The main change in the commit is to replace the `query_set_result`/
`query_each` delegation from Query to plans by specific classes
with a defined interface (#each_in_plan). The old method was
expecting the result of query_set_result to be an opaque type
that could only be iterated upon by calling #query_each
on the plan that generated it.
This allowed me to relatively easily rewrite the #roots operator on
transactions to deal with any depth of stacked transactions …

queries: generalize plan-iteration capabilities to all matchers

---

lib/roby/test/self.rb

This may be used to separate the test suite in different processes
(e.g. a fast/slow suite) while keeping a common coverage report.

allow passing a simplecov command name through the test command line

---

lib/roby/event_constraints.rb
lib/roby/task_structure/dependency.rb
test/droby/v5/test_droby_dump.rb
test/task_structure/test_dependency.rb

I've been wondering one time too many about whether the info had
been modified in-place. Just freeze the bloody thing.
(For the record, always wondered, has not happened in a very long time)

core: freeze dependency information

---

lib/roby/task_arguments.rb
test/test_task_arguments.rb

The class is meant to match Hash's base API as much as possible,
and #key? is preferred by rubocop. Note that (as documented),
one should prefer {#set?} or {#assigned?}

define TaskArguments#key? and deprecate #has_key?

---

Rakefile
lib/roby/app.rb
lib/roby/app/rake.rb
lib/roby/cli/gen/actions/test.rb.erb
lib/roby/cli/gen/app/.rubocop.yml
lib/roby/cli/gen/app/Rakefile
lib/roby/cli/gen/class/test.rb.erb
lib/roby/cli/gen/module/test.rb.erb
lib/roby/cli/gen/roby_app/config/robots/robot.rb.erb
lib/roby/cli/gen/task/test.rb.erb
lib/roby/test/aruba_minitest.rb
manifest.xml
test/cli/test_gen_main.rb

Test and linting can now be controlled by the JUNIT, RUBOCOP and
REPORT_DIR environment variables. Their output is placed in
REPORT_DIR if set, `$srcdir/.test-results` if not
Apps that mean to use Rubocop are expected to call {Roby::App::Rake.
Rubocop is enabled automatically if available when RUBOCOP is set to
anything but 0 or 1. It is disabled if set to 0. It is enabled, and will fail if
not present, when set to 1. Rubocop generates a junit report if JUNIT
is set to 1, the output dir being controlled by REPORT_DIR
Each robot test now gets its own test output, while they previously were happily
overwriting each other.

Improve test and linting support in apps

---

Rakefile
lib/roby/droby/logfile/client.rb
lib/roby/interface/rest/server.rb
lib/roby/interface/tcp.rb
test/cli/test_base.rb

Our internal CI based on [Buildbot and Kubernetes workers](https://github.com/tidewise/buildbot-ci/) has different quirks than Travis.
- One thing is that the UI is available (it's not in Travis) and the UIC must be run before the tests.
- Another is an issue with how Kubernetes defines 'localhost', which caused problems in connection checks (see 8e54ad9)
With this PR, both Roby and Syskit tests pass.

fix running tests within the buildbot CI

---

lib/roby/test/execution_expectations.rb
test/test/test_execution_expectations.rb

This adds two small functionalities to the existing expectations, with the aim to be able
to do small changes to existing expectations without having to create a whole new one
each time:
- `filter_result_with` allows to change the result returned by an expectation
- `achieve` and `maintain` now accept a block as description, to allow for a
more dynamic description (as e.g. `expected 10 samples, received 5`)

test: improve the ability to reuse expectations 

---

lib/roby/cli/gen/helpers.rb

The Style/Documentation cop ignores what looks like namespaces, but
Roby's usage of DSL-like methods breaks that detection. So, some
generated files trigger Style/Documentation.
Add `# :nodoc:` to silence the cop for what we know are namespaces.
Note that this never includes the class that is being generated, which
*will* have to be documented.

gen: add # :nodoc: to the innermost generated module

---

lib/roby/interface/rest/server.rb
lib/roby/interface/rest/test.rb
test/interface/rest/test_test.rb

This allows for API tests to manipulate the internal storage's
contents (for unit-testing) instead of being restricted to blackbox
tests.

test: give access to Roby storage in REST::Test

---

lib/roby/actions/action.rb
lib/roby/actions/models/action.rb
lib/roby/actions/models/method_action.rb
lib/roby/app.rb
lib/roby/cli/main.rb
lib/roby/coordination/models/actions.rb
lib/roby/coordination/models/base.rb
lib/roby/coordination/models/script.rb
lib/roby/coordination/models/task_from_action.rb
lib/roby/droby/logfile/writer.rb
lib/roby/event_generator.rb
lib/roby/interface/client.rb
lib/roby/interface/job.rb
lib/roby/models/task.rb
lib/roby/models/task_event.rb
lib/roby/support.rb
lib/roby/task.rb
roby.gemspec
test/test_task.rb

One important tidbit introduced in this PR are the `sanitize_keywords_to_array` and `sanitize_keywords_to_hash` helpers. They handle inconsistencies in Ruby 2.7 (compared to previous Rubies) for calls that mix strings and symbols in the last hash, such as
~~~
provides MODEL, "some" => "mapping", some: keywords
~~~

normalize some calls that use keyword arguments to use the ** splat

---

lib/roby/task.rb
test/test_task.rb

Otherwise, defining a `poll` block at the class level would require
knowing whether the superclass has a poll block or not. With this,
one has to unconditionally call `super()`.
Note that existing compositions/tasks won't be affected (since they
already do not have a superclass poll block)
Ideally, these blocks would not interact with each other. But in the
spirit of "document, don't change", only make this bit a little bit
nicer.

define an empty poll handler so that the class-level poll blocks can call super()

---

lib/roby/test/run_planners.rb
test/test/test_run_planners.rb

Otherwise, the user will get a cryptic error message. This is in
addition a rather common occurence when doing the common
`run_planner(find_tasks(M).first)`

test: validate that the argument is a task in run_planners

---

lib/roby/interface/droby_channel.rb

It seems that Ruby 2.7 has seen some effort w.r.t. fixing race
conditions related to autoloading. Unfortunately, it also seems
that it in our case we hit some lock contention or something.
Pre-load the Websocket classes. This fixes a Syskit interface
connection taking minutes on "real" links (i.e. non-loopback)
instead of seconds.

workaround performance issue on first connection in Ruby 2.7

---

.rubocop_todo.yml
lib/roby/app.rb
lib/roby/app/robot_names.rb
lib/roby/test/aruba_minitest.rb
test/app/test_run.rb

This was simply broken. The @robots instance variable was magically
created the first time it was accessed, which of course ended up
being at the wrong time.
Create it in #initialize and update it on app.yml loading using
a separate load_config_yml method. And add tests.

app: fix loading robot types from app.yml

---

lib/roby/app.rb

This is useful in the IDE, to be able to reload the models while
some --set options were given.

app: apply the configuration from --set arguments after reload

---

roby.gemspec

Versions between 0.83 and 0.89.0 have a bug that triggers on Roby.
Versions after 0.89.0 have a breaking change in the way
CyclomaticComplexity counts the complexity, which also breaks
on roby.
Stick to the last working version for now

fix rubocop version to 0.83.0

---

lib/roby/execution_engine.rb
test/test_execution_engine.rb

Depends on:
This alternate codepath was introduced a long time ago, in a attempt
to speed up garbage collection in some cases. The problem at the time
was that garbage collection passes would only remove the toplevel tasks.
This is not an issue anymore, as we do as many passes as possible,
internally to the method as well as during the execution cycle.
This piece of code was actually the source of a longstanding but never
fixed grave bug that manifested itself in Syskit, with running tasks
ending having nil execution agent. I finally managed to have a way
to reproduce (even if it is random and would take anywhere from 1
min to 1 hour). This reproducing case will be added to Syskit as
a stress test.
Syskit uses the `#can_finalize?` predicate to ensure that tasks
that are being configured …

core: remove GC short path for plans that have only pending or finished tasks

---

lib/roby/app.rb
lib/roby/app/scripts/run.rb
lib/roby/cli/gen/app/config/app.yml
lib/roby/droby/event_logger.rb
lib/roby/droby/event_logging.rb
lib/roby/droby/null_event_logger.rb

I started wondering why connecting to a running system was
simply **so slow**. It was always painfully slow, but I felt
it became a lot worse.
Turns out that timepoint logging, a feature that has been added
a few years back, is actually very verbose (timepoints have long
names, which are repeated sometimes multiple times per cycle). On
our systems, timepoints were by far the biggest part of an event log,
causing logs that should be in the hundred of MB to be multiple GBs.
This commit disables them by default - even I use them only in very
specific cases - and allow to re-enable them both through app.yml
and via the command line.

allow to enable or disable timepoint logging

---

lib/roby/test/event_reporter.rb

Turns out I didn't check the state of CI before merging #187. Sorry.

test: add missing definition for log_timepoints? in the test event reporter

---

lib/roby/interface/rest/server.rb
lib/roby/interface/rest/task.rb
test/interface/rest/test_server.rb
test/interface/rest/test_task.rb

- this commit disables the logging and error reporting middlewares by default. They are
very VERY noisy - to the point of unusability - in polling situations
- it allows the caller to inject a storage object (to handle roby_storage), which allows to
initialize the API locally with some values coming from e.g. arguments instead of having
to get everything from globals

improve "configurability" of Interface::REST server and task

---

lib/roby/task_structure/dependency.rb
test/task_structure/test_dependency.rb

I hit a bug where two Syskit components would get merged in a way that
the same fullfilled model, which had tags, was merged over and
over again. Exponentials ... Who does not like those ?
Anyways, the tag list is supposed to be small, so I preferred
keeping the array and calling uniq! afterwards on it

core: remove duplicate tags when merging fullfilled models

---

lib/roby/app/scripts/shell.rb
lib/roby/test/aruba_minitest.rb
test/cli/test_main.rb

Shell-related test started failing in CI because Readline was not defined. It turned out that the shell was not compatible with the gemified irb, which was pulled in some workspaces by iruby.
This pull request fixes the problems related to this interdependency.

cli: fix 'shell' when under the irb gem

---

lib/roby/droby/logfile.rb
lib/roby/droby/logfile/index.rb
lib/roby/droby/logfile/reader.rb

This is to be used for log management/processing (e.g. repairing
truncated logs)

droby: separate log reading/writing code into reusable bits

---

lib/roby/test/execution_expectations.rb

While #each_original_exception allowed to find the Exception subclasses,
we had no way to check the ExecutionException objects (to e.g. look
at the trace or origin of an error).

test: define UnexpectedErrors#each_execution_exception

---

lib/roby/event_generator.rb
lib/roby/executable_plan.rb
lib/roby/execution_engine.rb
lib/roby/plan.rb
lib/roby/standard_errors.rb
lib/roby/task.rb
test/test_event_generator.rb
test/test_executable_plan.rb
test/test_execution_engine.rb
test/test_task.rb

The quarantine code was a very old concept, that never really got
overhauled. It's trying to handle one of the dark alleys of state
management: what to do when tasks don't want to get stopped (or,
even worse, fail to).
When mapping an external process to a Roby task, it was also meant
to map the "I don't know what's the state of the remote process
anymore" situation. I.e. what to do when things go _really_ wrong.
The (really old) reaction was to isolate the task and let it be.
Turns out that by removing its relationships, we also remove the
ability for   Roby to figure out that something is wrong (since
we removed the dependencies). This is fine as long as the quarantine
was the byproduct of the GC process (the I can't stop / I don't want
to stop) when figured out by the garbage …

rework how quarantined tasks are handled

---

lib/roby/test/execution_expectations.rb
test/test/test_execution_expectations.rb

Some tests may generate some side-effects that are not strictly part
of the test, but do trigger the unexpected error checks in the test
harness.
If these side-effects are permanent, one can add the matching predicate
to the expectations. However, it may also be the byproduct of a race,
in which case it may or may not happen.
The `ignore_errors_from` predicate makes sure that the expectations
do not generate these unexpected errors, while still not demanding
that the predicate matches.
For instance, some Syskit tests check the runtime behavior of killing
the deployment while a long remote call is in progress. This must always
produce the aborted_event emission (which we test for), but also -
depending on timing - may raise ComError at the point of call *before*
aborted is emitted, which …

feat(app): define the ignore_errors_from predicate

---

lib/roby/test/droby_log_helpers.rb

Those are used to test some log processing scripts, and the scripts
now need the index.

test: export 'cycle_index' in the stats of logs generated by the droby helpers

---

lib/roby/app.rb
lib/roby/app/scripts/run.rb

It was - very unnecessarily - started by 'test'

fix(app): start the log server only in 'run'

---

lib/roby/droby/logfile/server.rb

There is a small window between the server's #accept and the time
where the socket is registered. This causes this particular socket
to not be closed if the server gets interrupted in the middle
Yet another reason why it's a bad idea to have exceptions getting
raised in the middle of anywhere.
Register the socket right away to avoid this problem.

fix(droby): race condition in Logfile::Server

---

lib/roby/test/execution_expectations.rb
test/test/test_execution_expectations.rb

Some predicates, namely have_error_matching, caches information
in update_match that it uses in other methods (in this case,
relates_to_error?)
Make sure IgnoreErrorFrom#update_match calls them so that the rest
works as expected

test: fix ignore_errors_from(have_error_matching ...)

---

lib/roby/standard_errors.rb
lib/roby/task.rb
test/task_structure/test_executed_by.rb
test/test/test_execution_expectations.rb
test/test_task.rb

In most cases, the reason would be a CodeError centered on the task
itself. However, that's not always the case. For instance, if the
task fails to start because of an execution agent failure, we end
up breaking the chain of explanations (we get Task#failure_reason
the terminal event of the deployment, without explanation about why
they are related).
This commit transform non-errors, non-localized errors and/or
localized errors from other objects into a FailedToStart exception
to be stored in failure_reason. It fixes issues in execution
expectations, where MissionFailed errors would be reported as
unexpected even if the source event was indeed expected.

fix(core): do not set Task#failure_reason to an arbitrary object in Task#mark_failed_to_start

---

lib/roby/app.rb

Triggered during CI when a starting app was killed, which changed the order of requires (it seems)

fix: missing require

---

lib/roby/droby/plan_rebuilder.rb
lib/roby/gui/plan_dot_layout.rb
lib/roby/gui/relations_view/relations_canvas.rb
test/droby/test_event_logging.rb

PlanRebuilder keeps arrays for event-related propagation information,
but was not storing the time these propagation events happened. This
was fine so far for roby-log display, which is not listing anything,
but fails utterly to analyze the list of propagation.
Change the format of these arrays. This does not change the log format

feat(log): add time in PlanRebuilder's event-related arrays

---

lib/roby/cli/log.rb

This allows to specify a log file in a non-standard location (e.g.
from a syskit datastore)

feat(cli): define --index-file to roby-log display

---

lib/roby/droby/logfile/server.rb

If the signal arrives during the write_nonblock call, it would
be interpreted as a communication error, which removes the client
but does not quit the server.

fix(cli): DRoby::Logfile::Server not always quitting after a SIGINT

---

lib/roby/droby/logfile/server.rb
lib/roby/droby/rebuilt_plan.rb
lib/roby/gui/relations_view/relations_canvas.rb

We (mis)use the relations canvas to display a task's "event cloud". After the last changes in the format of emitted_events,
how this code was using the arrays got broken. This fixes it.
Fixes https://github.com/rock-core/tools-syskit/issues/313

fix: wrong format for RebuiltPlan#emitted_events and called_generators in RelationsCanvasTask

---

lib/roby/test/self.rb

Tests still rely on the existence of the global Roby.app. However,
while we do reset the test's plan instance at every run, Roby.app.plan
does not get reset which creates inconsistencies.
Use Application#reset_plan to make sure the two are in sync.

fix(test): reset Roby.app.plan in test setup

---

lib/roby/coordination/task_script.rb
lib/roby/tasks/external_process.rb
lib/roby/test/execution_expectations.rb
lib/roby/transaction/event_generator_proxy.rb
test/interface/async/test_action_monitor.rb
test/interface/async/test_interface.rb
test/test/test_execution_expectations.rb

I somehow had the wrong idea that timeout(...) was controlling how
long we would wait to make sure that the event is not emitted.
That turns out to not be the case. Add the `within:` argument
to specify that time, and set it to 0 by default. This matches
the current behavior (raise if an event is emitted within the first
cycle of execution)

feat(test): add the 'within' argument to not_emit

---

lib/roby/test/self.rb

There is already make_tmpdir, but I'd like to slowly migrate to Pathname
for filesystem access ... so define tmppath

fix: define make_tmppath

---

lib/roby/test/common.rb
lib/roby/test/teardown_plans.rb

The latter has a `plan` argument that is not present in the former
(and older) version.

fix: remove double-definition of #execute between test/common and test/expect_execution

---

Rakefile
lib/roby/tasks/external_process.rb
test/mockups/interruptible_external_process
test/tasks/test_external_process.rb

Because one cannot turn an interruptible task into non-interruptible,
Roby::Tasks::ExternalProcess is not interruptible by default to let
downstream users decide how it should be stopped.
Nonetheless, an easy way to use ExternalProcess was lacking. This commit
defines Roby::Tasks::ExternalProcess.interruptible_with_signal, as a way
to get an external process that can simply be interrupted with a signal
(SIGINT by default).

feat: define Roby::Tasks::ExternalProcess.interruptible

---

lib/roby/app.rb

The current discovery in `all` mode would add all libs from all dependent bundles. Libs are really the part that should be config-independent, and testing in a given bundle should be enough for another.
Moreover, it was also loading the test/actions/test_main.rb from all dependent bundles. This is nonsensical as Main is built by the robot config itself.
Both functionalities were introduced before the migration to the name-based test discovery in the local bundle, which now naturally covers both cases.

fix: remove excessive files in test file discovery

---

lib/roby/event_generator.rb
lib/roby/queries/localized_error_matcher.rb
lib/roby/test/execution_expectations.rb
test/queries/test_localized_error_matcher.rb
test/test/test_execution_expectations.rb

The error handling code would currently determine that an exception
raised by an event handler is caused by the event. Because of this
relationship,
```
expect_execution { CODE }
.to { emit EVENT }
```
would not report an exception raised by an event handler of EVENT.
This commit makes sure that it's not the case anymore.

fix: do not let a { emit EVENT } statement hide a handler error

---

lib/roby/app.rb
test/test_app.rb

This PR fixes the search folder priority order in documentation and add a test to ensure that the order between general and specific configurations is always followed.

fix: search folder documentation

---

lib/roby/app.rb
lib/roby/cli/gen/roby_app/config/robots/robot.rb.erb
lib/roby/robot.rb
lib/roby/test/spec.rb

"shutdown" happens at the end of a run, but before cleanup. I've created this handler because the tests don't cleanup (way too costly), but we still need to remove the stuff that the controller / test itself might have been adding to the app.
Note that 'shutdown' as a stage in the app lifecycle already existed (which really shows its usefulness). What was missing is a user-visible handler.

feat: create the app shutdown handlers

---

lib/roby/task_arguments.rb

The current method was modifying the object in place, which would cause the following awkward situation:
```
obj = from_state.something
obj.bla
```
Which is already bad in general, but also means that any wrong code that would call a method missing could modify some unrelated default argument.

fix: make method_missing return a new object in DelayedArgumentFromObject

---

lib/roby/cli/gen/roby_app/config/init.rb
lib/roby/support.rb
lib/roby/tasks/external_process.rb
test/tasks/test_external_process.rb

ExternalProcess are actually spawning subprocesses in roby tests, which goes against the point of the "simulation" mode, where we don't start subprocesses / external processes.
This commit adds a stub_subprocess argument to the task, and a global ExternalProcess.stub_in_roby_simulation_mode flag to set it automatically during tests. This flag is false for backward compatibility reasons.

feat: add a stub mode to ExternalProcess, and a global flag to control it

---

lib/roby/actions/action.rb
lib/roby/actions/models/action.rb
lib/roby/actions/models/interface_base.rb
test/actions/models/test_action.rb
test/actions/test_action.rb

These are meant for the model-based tools to be able to call simple
actions that have required arguments, when the resulting plan is not
argument-dependent and needs to be analyzed. For instance, Syskit
mass-check predicates (e.g. assert_can_deploy) can get action state
machines and/or method actions to be called and check that the Syskit
bits are viable.
This covers the 80% of the use-cases, for the rest the calls will
have still to be done manually.

feat: example arguments for action required arguments

---

lib/roby/droby/v5/droby_constant.rb
test/droby/v5/test_droby_constant.rb

Useful for backward compatibility reasons to "trace" names that have changed

feat: allow converting constants from the log file into new names

---

lib/roby/coordination/models/actions.rb
lib/roby/task.rb
test/coordination/models/test_action_state_machine.rb
test/test_task.rb

Action state machines do not need to be tied to an action interface.
This pull request adds Task#action_state_machine to create one
on-the-fly on a task instance.

feat: define Roby::Task#action_state_machine

---

lib/roby/test/assertion.rb

The old namespace was removed in 5.19

fix: the MiniTest namespace has been removed, it is only Minitest now

---

lib/roby/coordination/models/action_state_machine.rb
lib/roby/coordination/models/base.rb
lib/roby/test/validate_state_machine.rb
test/coordination/test_action_state_machine.rb

Creates a way for setting states' names explicitly in action state machines

feat: set state name in action state machine

---

lib/roby/droby/logfile.rb

A few months ago, we extended Roby::Actions::Models::Action::Argument to add the "example" fields. Unfortunately, ruby won't load struct of the old type because the amount of fields have changed - something that does not happen with classes.
Beyond showing again that the current log format is simply wrong, it makes all older log files un-readable. This commit hacks its way around the problem by re-defining the constant with the old struct definition.

fix: manage loading older log files

---

lib/roby/event_generator.rb
lib/roby/plan.rb
lib/roby/relations/bidirectional_directed_adjacency_graph.rb
lib/roby/task.rb
test/relations/test_bidirectional_directed_adjacency_graph.rb
test/test_event_generator.rb
test/test_task.rb

The current implementation of plan= would nil @relation_graphs on
plan objects, which led to any relation-related method to fail on
a finalized object.
This commit sets instead null relation graphs, which will then treat
finalized tasks as single tasks without any relations.
[sc-33156]

fix: access to relation-related methods on finalized tasks

---

lib/roby/droby/plan_rebuilder.rb
lib/roby/droby/rebuilt_plan.rb
test/droby/test_event_logging.rb

Regularly, but not often, log replay would fail with
undefined method `failed_emissions' for #<Roby::TemplatePlan`
I finally took the time to get into it. Turns out that the Roby logs (and therefore the engine) sometimes finalizes a task while there are still some events pending - in this case a failed_event
What happens is that the exception leads to a finalization, and later (during processing), some exception handler marks events as emission_failed.
While the right fix would be to stop this behavior altogether, we also have to deal with existing logs that show this behavior. Process finalizations at the end of the cycle instead of immediately to workaround. Note that this is probably what also will be done at runtime.

fix: fix a longstanding problem during log replay

---

lib/roby/exceptions.rb
lib/roby/test/execution_expectations.rb
test/test/test_expect_execution.rb

Exception#pretty_print only shows the exception message nowadays.

fix; show complete exception traces when displaying exceptions as reason for unachievability

---

lib/roby/droby/logfile/server.rb
test/cli/test_display.rb

In tests, this led to the client socket not being closed, which in turn means that the connection is not closed. In practice, the display server is executed in its own thread which means that the socket was closed nonetheless.
The tests were passing if they finished the server thread before it accepted the socket, and would fail otherwise. Moreover, there was another race if the server thread would have time to send initial data.

fix: race condition in Logfile::Server between acceptation of a socket and its registration

---

lib/roby/droby/v5/droby_dump.rb

The is used for log replaying. Checking for equality makes no sense there since the remote *is* the source of truth. Define TaskArguments#force_merge! and use it there.
This should solve the all-too-common "can't merge arguments" error in the Syskit IDE.

fix: force-merge arguments coming from the DRoby protocol

---

lib/roby/app/scripts/test.rb

This makes it easier to select groups of tests with TESTOPTS when using `rake test`

fix: allow passing globs to `roby test`

---

lib/roby/app.rb
lib/roby/app/cucumber/controller.rb
lib/roby/app/scripts/run.rb
lib/roby/cli/base.rb
lib/roby/exceptions.rb
lib/roby/interface/tcp.rb
lib/roby/test/aruba_minitest.rb
lib/roby/test/roby_app_helpers.rb
test/app/cucumber/test_controller.rb
test/app/fixtures/cli_base.rb
test/app/test_run.rb
test/cli/test_base.rb
test/cli/test_gen_main.rb
test/cli/test_main.rb
test/interface/async/client_server_test_helpers.rb
test/interface/async/test_interface.rb
test/test_app.rb

fix: start the shell interfaces on random ports during tests

---

lib/roby/test/execution_expectations.rb

Note that there are other places in Roby and Syskit, but since they are not test-specific, it will be more difficult to fix them.

fix: make the execution harness impervious to the usage of Timecop.freeze

---

lib/roby/coordination/action_state_machine.rb
test/coordination/test_action_state_machine.rb

Current state was not being used at all, this assigns it at the state machines start and during transitions.

fix: register the current state for action state machines

---

lib/roby/test/aruba_minitest.rb

We got some "timed out on stop" in CI when didnt have enough CPU available. I changed the aruba minitest interface to take an exit timeout as a kwarg, and set it to 45s as default

fix: increase aruba exit timeout to 45s

---

test/interface/rest/test_server.rb

We've got a heisenbug that fails on the `after do` block claiming that it timed out waiting for server start. However, the server shouldnt really start, as we are mocking the thread creation, somehow the thread is still alive when it gets to the after do block. The idea is to force garbage collection to run by calling server stop before after do.

fix: force garbage collection on server thread

---

lib/roby/app/rake.rb

Not synching some `puts` when sync is on would result in a very messy output when running rake in parallel.

fix: move all STDOUT.puts to be sync when sync is on

---

lib/roby/app/scripts/test.rb

This is done by minitest/autorun, and some plugins require it to function (e.g. minitest-stackprofit)

fix: run minitest' after blocks at the end of `roby test`

---

lib/roby/app/scripts/test.rb

Reverts rock-core/tools-roby#289
Rubocop is failing and this is the culprit, its not critical so we are reverting and fixing rubocop

Revert "fix: run minitest' after blocks at the end of `roby test`"

---

lib/roby/actions/action.rb
lib/roby/actions/models/action.rb
lib/roby/coordination/models/variable.rb
lib/roby/interface/v2/protocol.rb
lib/roby/models/arguments.rb
lib/roby/support.rb
test/actions/test_action.rb
test/interface/v2/test_channel.rb
test/models/test_arguments.rb

This fixes a bug in the test harness where syskit would be unable to deploy multiple actions together when:
- One of the tasks is a toplevel task that depends on another task
- The second task is one of the deployed together actions
The issue appeared as a failed merge attempt complaining that a Variable doesnt have the strong? method
By looking further into it, we realized that this happened because when the toplevel task shares used definitions with the sub task, they would have delayed variable references instead of the example arguments (since we dont resolve the example arguments ourselves). That way, syskit was basically trying to merge "some defined value" and "var:variable_name", which should not be possible. 
The fix to that comes in two parts:
1. Adding the strong? and …

fix: add example to task arguments and inject these examples in syskit_deploy_in_bulk

---

lib/roby/actions/models/action.rb

Missed directing the VoidClass/Void to reference the roby one that was created.

fix: point to roby void class

---

lib/roby/app.rb
test/test_app.rb

When called in Robot.init, register_app is followed by at least one call to update_load_path, which ensures that the app (and its lib/) is added to $LOAD_PATH
This commit adds some search path modification helpers, and ensures that update_load_path is called whenever the search path is modified.

fix: make sure $LOAD_PATH is updated even if register_app is called outside init

---

lib/roby/interface/rest/api.rb

In some order of require, Helpers would be resolved to Grape::API::Helpers (that's a mystery to me ... I think maybe something Grape is doing ?) instead of Roby::Interface::REST::Helpers.

fix: add missing require

---

lib/roby/interface/v2/tcp.rb

fix: interpret a TimeoutError during Client#initialize as a connection failure

---

.rubocop_todo.yml
lib/roby/event_structure/precedence.rb
lib/roby/relations/bidirectional_directed_adjacency_graph.rb
lib/roby/relations/incremental_transitive_closure.rb
test/relations/test_bidirectional_directed_adjacency_graph.rb
test/relations/test_incremental_transitive_closure.rb
test/suite_relations.rb

Creating an incremental transitive closure graph representation to help optimizing reachable calls. Which allows incremental updates to a directed graph while maintaining its transitive closure.
Using this transitive closure graph in precedence graph. To optimize when possible the reachable call speed.
Benefits when running a full robot test:
After running 5 times for caching and 10 times for timing:
Went from 401.0075 seconds to 388.393  seconds

feat: incremental transitive closure graph

---

lib/roby/plan.rb
test/test_plan.rb

apply one task plan marks to another
EDIT: At first I tried to mark the "merging onto" task just as the "merged task", that is, marking (add) and _unmarking_ (subtracting) the merging onto task so it was exactly marked as the merged task. This breaks the `it "does not change anything if asked to deploy the same composition twice"` test, because it removed the _mission mark_ from compositions already in the _real plan_

feat: copy marks

---

lib/roby/app.rb
test/test_app.rb

Add possibility to not use app name when logging, and unit test the #log_base_dir app method.

feat: add possibility to not use app name when creating the log directory

---

lib/roby/relations/bidirectional_directed_adjacency_graph.rb

Because I would be suspicious of such a PR without a proper benchmark ... We do get roughly 3 to 4% improvement on a reverse micro-benchmark (note that `reverse` is a combination of `dup` and `reverse!`, the method that has been optimized)
Benchmark is:
```
require "roby"
require "benchmark/ips"
VERTICES = 150
FORWARD_EDGES = 2000
TIMES = 10_000
graph = Roby::Relations::BidirectionalDirectedAdjacencyGraph.new
vertices = VERTICES.times.map { Object.new }
FORWARD_EDGES.times.map do
to = from = vertices.sample
to = vertices.sample until to != from
graph.add_edge(from, to, Object.new)
end
Benchmark.ips do |x|
x.config(warmup: 2, time: 10)
x.report("graph reverse NEW") do
graph.reverse
end
x.report("graph reverse OLD") do
graph.reverse_old
end
end
```

chore: micro-optimization in graph reverse

---

lib/roby/interface/rest/server.rb
lib/roby/interface/rest/task.rb
lib/roby/interface/rest/test.rb
lib/roby/test/execution_expectations.rb
test/interface/rest/test_server.rb
test/interface/rest/test_task.rb
test/test/test_execution_expectations.rb
test/test_app.rb

Depends on:
The current behaviour was designed around the idea that few places would need to
interact with the execution thread in a non-thread-safe way. Reality is very
different, and bugs that come from the lack of synchronization are really hard
to track and debug.
This makes all calls run inside a ExecutionEngine#execute block. For more
fine-grained access, one can disable that behaviour and explicitly use
roby_execute, or do something like split the APIs and have two handlers, one
always synchronized and one always not.

fix: run all REST request handlers in the execution thread by default

---

lib/roby/queries/code_error_matcher.rb
test/queries/test_code_error_matcher.rb

CodeError may have an underlying exception or not (e.g. EmissionFailed is routinely created without an underlying exception). The corresponding matcher should really match all cases, and not only the one with "no exceptions"

fix: initialize CodeErrorMatcher to match any exception *or* no exceptions at all

---

lib/roby/test/expect_execution.rb
test/test/test_execution_expectations.rb

E.g. expect_execution { ... }
.to_achieve { ... }
Works with any expectation

feat: create shortcut `to_PREDICATE` for the very common single-predicate expectation

---

lib/roby/app.rb
test/test_app.rb

The objective is to add a robust way for external tools to know if a log dir is being managed by a roby/syskit process or not.
Supersedes https://github.com/rock-core/tools-roby/pull/317

feat: add log dir lock and unlock

---

lib/roby/standard_errors.rb
lib/roby/task.rb
lib/roby/test/execution_expectations.rb
test/test/test_execution_expectations.rb

The handler that turns CodeError into task-level errors in Roby::Task (e.g. fail_to_start or
internal_error_event) is overly specific (it only looks for CodeError). It is desirable to be able
to handle other errors the same way (cf. introduction of PropertyUpdatesError in Syskit, linked
to this PR)
This PR introduces the InternalTaskError type that is a simple subclass of LocalizedError
for this purpose.

feat: introduce the InternalTaskError type

---

lib/roby/test/execution_expectations.rb

On top of #327 
To avoid overly verbose tests, the execution expectation harness filters out "related errors". For instance, testing for `emit task.failed_event` will ignore all errors created by this emission.
This is great for user-facing tests, but the unit test suites of Syskit and Roby need an escape hatch. For now, I created the flag locally to use in a Syskit test case (which had the very issue of "not seeing" a plan error) so that later we can try turning it off for all tests in these two package's unit test suites (I'm expecting some work)

feat: define the filter_out_related_errors config flag in execution expectations

---

lib/roby/test/event_reporter.rb
lib/roby/test/spec.rb

The event reporter wasnt fully integrated, this finishes what was missing to the test suite.

fix: finish event reporter integration to test spec

---

lib/roby/app/scripts/test.rb

This is a workaround for a bug in simplecov. It calls Proc.new without a block, which is forbidden in recent (that is at least > 2.7)

fix: test end when SimpleCov is loaded but not enabled

---

lib/roby/support.rb

It's a method I've defined on Syskit and started to use quite a bit on all timeout-related code in telemetry/. Given its applicability, I think best to move it here.

feat: define Roby.monotonic_time

---

lib/roby/task_arguments.rb
test/test_task_arguments.rb

The principal two ways to interact with it (adding a new method to the path and specifying the expected type) actually were modifying the receiver, which leads to:
from_conf = Roby.from_conf.some.complex.path
from_conf.field0
from_conf.field1
to search for from_conf.field0.field1 ... Really not expected, and neither desired in this case.

fix: do not self-modify DelayedArgumentFromObject

---

lib/roby/queries/matcher_base.rb
lib/roby/queries/task_matcher.rb
test/queries/test_task_matcher.rb

The real bug here is the matcher API that modifies its receiver forever, that is:
matcher = find_tasks.executable
matcher.executable.first
will add `executable` to `matcher` (the first one). And will do it every single time. And then match all of them (sequentially). So, possibly, we could have millions of these predicates being checked forever and ever.
I believe changing the API will have to be done, but will take time and will have to be done gradually / in a conservative manner. This patch at least alleviates the major issue without changing the matcher's (horrible) behaviour

fix: do not register the same predicate twice in a matcher

---

lib/roby/state/open_struct.rb
lib/roby/state/open_struct_model.rb
test/state/test_open_struct.rb

The point of stable! was to have a mode where the structure of the OpenStruct tree could not be changed anymore, but the values could. There was actually a few bugs around this.
Additionally, remove compatibility with pre-2.0 Ruby (!)

fix: cleanup behaviour related to stable OpenStruct

---

lib/roby/schedulers/basic.rb
lib/roby/schedulers/temporal.rb
test/schedulers/test_temporal.rb

`schedule_as` indicates that a task should be considered for scheduling only if
another task is. This is used to schedule planning tasks at the point in time
where their planned task is considered for planning, in e.g. Syskit (so, deploy
a subnet only when it is needed)
However, because Syskit also has a strong constraint that all children of a
composition will be started with the composition, we implemented that the
executable? flag for compositions returns true only if the children of the
composition are also executable.
Combined, this leads to the following pattern to fail:
root.depends_on child
child.depends_on abstract
abstract.planned_by planning_task
planning_task.schedule_as abstract
Since child is not running, abstract cannot be scheduled and won't be planned,
which leads to …

fix: change the temporal scheduler to handle relationships between schedule_as and dependency

---

lib/roby/app.rb
test/test_app.rb

The previous implementation could only give priority to more specific
matches, which can be confusing. The prefer local flag returns matches
from the local app before any other matches from other registered apps when
the specific first flag is set. Otherwise, it changes nothing.

feat: add argument to prefer local path when order is specific first

---

lib/roby/app.rb

Forgot to add these in https://github.com/rock-core/tools-roby/pull/340

fix: pass prioritize root paths option forward in methods that call find_dirs

---

lib/roby/app/rake.rb

log test specific arguments. It helps in reproducing CI runs at developer's local machine

chore: display `roby test` arguments in Rake helpers
